<?php
use App\Models\Site;
use App\Services\{AddressSearch,PostcodeLookup};
use App\Settings\GeneralSettings;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Str;
use Illuminate\Validation\Rule;
use Livewire\Attributes\Title;
use Livewire\Component;

new #[Title('Site')] class extends Component {
 public ?Site $site=null; public string $query=''; public array $remote=[]; public bool $manual=false; public string $name=''; public string $address_line_1=''; public ?string $address_line_2=null; public ?string $town=null; public ?string $county=null; public string $postcode=''; public ?string $what_3_words=null; public ?string $google_place_id=null; public ?string $access_instructions=null;
 public function mount(?Site $site=null):void{$this->site=$site;$this->manual=(bool)$site;if($site)foreach(['name','address_line_1','address_line_2','town','county','postcode','what_3_words','google_place_id','access_instructions'] as $f)$this->{$f}=$site->{$f};}
 public function search(AddressSearch $search,GeneralSettings $settings):void{$this->validate(['query'=>['required','string','min:3','max:255']]);$this->remote=$search->suggestions($this->query,$settings);}
 public function chooseLocal(int $id):mixed{return $this->redirectRoute('crm.sites.update',Site::findOrFail($id),navigate:true);}
 public function chooseRemote(string $id,AddressSearch $search,GeneralSettings $settings):void{$data=$search->details($id,$settings);if(!$data){$this->addError('query','Address details could not be loaded.');return;}foreach($data as $f=>$v)$this->{$f}=$v;$this->manual=true;}
 public function enterManually():void{$this->address_line_1=$this->query;$this->manual=true;}
 public function save():mixed{Gate::authorize($this->site?'crm.site.update':'crm.site.create');$data=$this->validate(['name'=>['required','max:255'],'address_line_1'=>['required','max:255'],'address_line_2'=>['nullable','max:255'],'town'=>['nullable','max:255'],'county'=>['nullable','max:255'],'postcode'=>['required','max:20'],'what_3_words'=>['nullable','max:255'],'google_place_id'=>['nullable','max:255'],'access_instructions'=>['nullable','max:2000']]);$raw=Str::upper(preg_replace('/[^A-Z0-9]/i','',implode('|',[$data['address_line_1'],$data['address_line_2']??'',$data['town']??'',$data['county']??'',$data['postcode']])));$data['address_code']=hash('sha256',$raw);validator($data,['address_code'=>[Rule::unique('sites')->ignore($this->site?->id)]],['address_code.unique'=>'This address already exists. Select it from the local results.'])->validate();$this->site?$this->site->update($data):Site::create($data);return $this->redirectRoute('crm.sites.index',navigate:true);}
 public function validatePostcode(PostcodeLookup $lookup,GeneralSettings $settings):void{if($settings->postcode_validation_provider!=='postcodes_io')return;$result=$lookup->lookup($this->postcode);if(!$result){$this->addError('postcode','Postcode could not be validated.');return;}$this->postcode=$result['postcode'];$this->county=$this->county?:($result['admin_district']??$result['region']??null);}
 public function with():array{$term='%'.$this->query.'%';return ['local'=>strlen(trim($this->query))>=3?Site::where(fn($q)=>$q->where('name','like',$term)->orWhere('address_line_1','like',$term)->orWhere('town','like',$term)->orWhere('postcode','like',$term))->limit(10)->get():collect()];}
}; ?>
<section class="w-full p-6"><flux:heading size="xl">{{ $site?'Edit Site':'Create Site' }}</flux:heading><x-pages::shared.layout contentclass="max-w-3xl">@unless($manual)<div class="space-y-5"><div class="flex items-end gap-2"><div class="flex-1"><flux:input wire:model="query" label="Find an address" placeholder="Start with the first line, e.g. 8 Tatton Grove"/></div><flux:button type="button" variant="primary" wire:click="search">Search</flux:button></div><flux:error name="query"/>@if(strlen(trim($query))>=3)<flux:card><flux:heading size="sm">Local</flux:heading><div class="divide-y">@forelse($local as $result)<button type="button" wire:click="chooseLocal({{ $result->id }})" class="block w-full py-3 text-left hover:bg-zinc-50">{{ $result->formattedAddress() }}</button>@empty<flux:text class="py-3">No local matches.</flux:text>@endforelse</div></flux:card>@endif @if($remote)<flux:card><flux:heading size="sm">Remote</flux:heading><div class="divide-y">@foreach($remote as $result)<button type="button" wire:click="chooseRemote('{{ $result['id'] }}')" class="block w-full py-3 text-left hover:bg-zinc-50">{{ $result['label'] }}</button>@endforeach</div></flux:card>@endif<flux:button type="button" variant="ghost" wire:click="enterManually">Not listed above — add manually</flux:button></div>@else<form wire:submit="save" class="grid gap-5 sm:grid-cols-2"><flux:input wire:model="name" label="Site name" required/><flux:input wire:model="address_line_1" label="Address line 1" required/><flux:input wire:model="address_line_2" label="Address line 2"/><flux:input wire:model="town" label="Town / city"/><flux:input wire:model="county" label="County"/><div class="flex items-end gap-2"><div class="flex-1"><flux:input wire:model="postcode" label="Postcode" required/></div><flux:button type="button" wire:click="validatePostcode">Validate</flux:button></div><flux:input wire:model="what_3_words" label="What3Words"/><flux:textarea class="sm:col-span-2" wire:model="access_instructions" label="Instructions / easy to find"/><div class="flex justify-between sm:col-span-2">@unless($site)<flux:button type="button" variant="ghost" wire:click="$set('manual',false)">Back to search</flux:button>@endunless<div class="ml-auto flex gap-2"><flux:button :href="route('crm.sites.index')" variant="ghost">Cancel</flux:button><flux:button type="submit" variant="primary">Save</flux:button></div></div></form>@endunless</x-pages::shared.layout></section>
