<?php
use App\Models\{Company,Site};
use App\Support\CurrentCompany;
use Illuminate\Support\Facades\{Auth,DB,Gate,Storage};
use Illuminate\Support\Str;
use Illuminate\Validation\Rule;
use Livewire\Attributes\Title;
use Livewire\Component;
use Livewire\WithFileUploads;

new #[Title('Company')] class extends Component {
 use WithFileUploads;
 public ?Company $company=null; public int $step=1; public string $tab='details'; public string $name=''; public ?string $trading_name=null; public string $code=''; public ?string $email=null; public ?string $phone=null; public string $document_prefix=''; public bool $is_active=true; public ?string $registration_number=null; public ?string $vat_number=null; public ?string $brand_primary_color=null; public $logo=null;
 public array $headOffice=[]; public array $draftDepots=[]; public string $addressType='depot'; public ?int $editDepot=null; public ?int $editSite=null; public ?int $selectedSiteId=null; public bool $creatingAddress=false; public string $addressSearch=''; public string $site_name=''; public string $site_address_line_1=''; public ?string $site_address_line_2=null; public ?string $site_town=null; public ?string $site_county=null; public string $site_postcode='';
 public function mount(CurrentCompany $currentCompany,?Company $company=null):void { if($company&&!Auth::user()->hasRole('Super-Admin'))abort_unless($company->id===$currentCompany->id(Auth::user()),404); $this->company=$company; if($company)foreach(['name','trading_name','code','email','phone','document_prefix','registration_number','vat_number','brand_primary_color','is_active'] as $f)$this->{$f}=$company->{$f}; }
 private function details():array{return ['name'=>['required','max:255'],'trading_name'=>['nullable','max:255'],'code'=>['required','max:20',Rule::unique('companies')->ignore($this->company?->id)],'email'=>['nullable','email'],'phone'=>['nullable','max:100'],'is_active'=>['boolean']];}
 private function branding():array{return ['document_prefix'=>['required','max:20'],'registration_number'=>['nullable','max:100'],'vat_number'=>['nullable','max:100'],'brand_primary_color'=>['nullable','regex:/^#[0-9A-Fa-f]{6}$/'],'logo'=>['nullable','image','max:2048']];}
 public function next():void { if($this->step===1)$this->validate($this->details()); if($this->step===2&&$this->headOffice===[]){$this->addError('headOffice','Add a head office address before continuing.');return;} $this->step=min(3,$this->step+1); }
 public function back():void{$this->step=max(1,$this->step-1);}
 public function address(string $type,?int $index=null,?int $site=null):void { if($type==='head'&&$this->company)$site=null; $this->reset(['selectedSiteId','creatingAddress','addressSearch','site_name','site_address_line_1','site_address_line_2','site_town','site_county','site_postcode']); $this->addressType=$type;$this->editDepot=$index;$this->editSite=$site; $row=$site?Site::findOrFail($site)->only(['name','address_line_1','address_line_2','town','county','postcode']):($type==='head'?$this->headOffice:($index===null?[]:$this->draftDepots[$index])); foreach($row as $k=>$v)$this->{'site_'.($k==='name'?'name':$k)}=$v; $this->creatingAddress=$site!==null||$row!==[]; Flux::modal('address')->show(); }
 public function updatedSelectedSiteId(?int $siteId):void { if(!$siteId)return; $site=Site::findOrFail($siteId); if($this->company){$this->company->sites()->syncWithoutDetaching([$site->id]);if($this->addressType==='head'){$this->company->update(['home_site_id'=>$site->id]);$this->company->refresh();}Flux::modal('address')->close();return;} foreach($site->only(['name','address_line_1','address_line_2','town','county','postcode']) as $k=>$v)$this->{'site_'.($k==='name'?'name':$k)}=$v; $this->creatingAddress=true; }
 public function createAddress():void { $name=trim($this->addressSearch);$this->reset(['selectedSiteId','editSite','site_name','site_address_line_1','site_address_line_2','site_town','site_county','site_postcode']);$this->site_name=$name;$this->creatingAddress=true; }
 private function addressData():array{return $this->validate(['site_name'=>['required','max:255'],'site_address_line_1'=>['required','max:255'],'site_address_line_2'=>['nullable','max:255'],'site_town'=>['nullable','max:255'],'site_county'=>['nullable','max:255'],'site_postcode'=>['required','max:20']]);}
 private function site(array $d):array{$raw=Str::upper(preg_replace('/[^A-Z0-9]/i','',implode('|',$d)));return ['name'=>$d['site_name'],'address_line_1'=>$d['site_address_line_1'],'address_line_2'=>$d['site_address_line_2'],'town'=>$d['site_town'],'county'=>$d['site_county'],'postcode'=>Str::upper($d['site_postcode']),'address_code'=>hash('sha256',$raw)];}
 public function saveAddress():void { $d=$this->addressData(); if($this->company){Gate::authorize('crm.site.update');$s=$this->editSite?Site::findOrFail($this->editSite):new Site();$s->fill($this->site($d))->save();$this->company->sites()->syncWithoutDetaching([$s->id]);if($this->addressType==='head'){$this->company->update(['home_site_id'=>$s->id]);$this->company->refresh();}}elseif($this->addressType==='head')$this->headOffice=$d;elseif($this->editDepot===null)$this->draftDepots[]=$d;else $this->draftDepots[$this->editDepot]=$d; Flux::modal('address')->close(); }
 public function removeDepot(int $i):void{unset($this->draftDepots[$i]);$this->draftDepots=array_values($this->draftDepots);}
 public function detachDepot(int $siteId):void { abort_unless($this->company,404);Gate::authorize('admin.company.update');abort_if($siteId===$this->company->home_site_id,422,'The head office cannot be removed as a depot.');abort_unless($this->company->sites()->whereKey($siteId)->exists(),404);$this->company->sites()->detach($siteId);Flux::toast(text:'Depot removed from company',variant:'success'); }
 public function save():mixed { Gate::authorize($this->company?'admin.company.update':'admin.company.create');if($this->company){$data=$this->tab==='branding'?$this->validate($this->branding()):$this->validate($this->details());if(array_key_exists('logo',$data)){unset($data['logo']);if($this->logo)$data['logo_path']=$this->logo->store('company-logos','public');}$this->company->update($data);Flux::toast(text:'Company updated',variant:'success');return null;}$d=$this->validate($this->details());$b=$this->validate($this->branding());if($this->headOffice===[]){$this->step=2;$this->addError('headOffice','Add a head office address before saving.');return null;}unset($b['logo']);if($this->logo)$b['logo_path']=$this->logo->store('company-logos','public');DB::transaction(function()use($d,$b){$this->company=Company::create($d+$b);$h=Site::create($this->site($this->headOffice));$this->company->sites()->attach($h);$this->company->update(['home_site_id'=>$h->id]);foreach($this->draftDepots as $x){$site=Site::create($this->site($x));$this->company->sites()->attach($site);}});return $this->redirectRoute('settings.companies.index',navigate:true); }
 public function with():array{return ['office'=>$this->company?->homeSite,'depots'=>$this->company?$this->company->sites()->whereKeyNot($this->company->home_site_id)->orderBy('name')->get():collect(),'siteOptions'=>Site::orderBy('name')->get()];}
}; ?>
<section class="w-full">@include('partials.settings-heading',['section'=>$company?'Update company':'Create company'])<x-pages::settings.layout contentclass="mt-5 w-full max-w-5xl"><div class="mb-5 flex justify-between"><div><flux:heading size="lg">{{ $company?'Update company':'Create company' }}</flux:heading><flux:text>{{ $company?'Manage company details, addresses and branding.':'Complete each guided step.' }}</flux:text></div><flux:button variant="ghost" :href="route('settings.companies.index')">Back</flux:button></div>
@if($company)<div class="mb-5 flex gap-2 border-b pb-3">@foreach(['details'=>'Company','addresses'=>'Addresses','branding'=>'Branding'] as $key=>$label)<flux:button type="button" :variant="$tab===$key?'primary':'ghost'" wire:click="$set('tab','{{ $key }}')">{{ $label }}</flux:button>@endforeach</div>@else<div class="mb-5 grid grid-cols-3 gap-3">@foreach([1=>'Company details',2=>'Addresses',3=>'Branding'] as $n=>$label)<div class="rounded border p-3 {{ $step===$n?'border-blue-500 bg-blue-50':'' }}"><small>STEP {{ $n }}</small><br>{{ $label }}</div>@endforeach</div>@endif
<form wire:submit="save" class="space-y-5">
@if(($company&&$tab==='details')||(!$company&&$step===1))<flux:card class="grid gap-5 md:grid-cols-2"><flux:input wire:model="name" label="Company name" required/><flux:input wire:model="trading_name" label="Trading name"/><flux:input wire:model="code" label="Shortcode" required/><flux:switch wire:model="is_active" label="Active"/><flux:input wire:model="phone" label="Phone"/><flux:input wire:model="email" type="email" label="Email"/></flux:card>
@elseif(($company&&$tab==='addresses')||(!$company&&$step===2))<div class="grid gap-5 md:grid-cols-2"><flux:card><div class="mb-4 flex justify-between"><flux:heading>Head Office</flux:heading><flux:button type="button" size="sm" wire:click="address('head',null,{{ $office?->id??'null' }})">{{ ($office||$headOffice)?'Change':'Add' }}</flux:button></div>@php($h=$company&&$office?['site_name'=>$office->name,'site_address_line_1'=>$office->address_line_1,'site_address_line_2'=>$office->address_line_2,'site_town'=>$office->town,'site_county'=>$office->county,'site_postcode'=>$office->postcode]:$headOffice)@if($h)<address class="not-italic">@foreach(array_filter($h) as $line)<span class="block">{{ $line }}</span>@endforeach</address>@else<flux:text>No address added.</flux:text>@endif<flux:error name="headOffice"/></flux:card><flux:card><div class="mb-4 flex justify-between"><flux:heading>Depots</flux:heading><flux:button type="button" size="sm" wire:click="address('depot')">Add</flux:button></div><flux:table><flux:table.rows>@forelse($company?$depots:$draftDepots as $i=>$d)<flux:table.row><flux:table.cell>{{ $company?$d->name:$d['site_name'] }}</flux:table.cell><flux:table.cell align="end"><flux:button type="button" size="xs" icon="pencil" aria-label="Edit depot" wire:click="address('depot',{{ $company?'null':$i }},{{ $company?$d->id:'null' }})"/>@if($company)<flux:button type="button" size="xs" variant="danger" icon="trash" aria-label="Remove depot" wire:click="detachDepot({{ $d->id }})" wire:confirm="Remove this depot from the company?"/>@else<flux:button type="button" size="xs" variant="danger" icon="trash" aria-label="Remove depot" wire:click="removeDepot({{ $i }})"/>@endif</flux:table.cell></flux:table.row>@empty<flux:table.row><flux:table.cell>No depots.</flux:table.cell></flux:table.row>@endforelse</flux:table.rows></flux:table></flux:card></div>
@else<flux:card class="grid gap-5 md:grid-cols-2"><flux:input wire:model="logo" type="file" label="Logo"/><flux:input wire:model="document_prefix" label="Document prefix" required/><flux:input wire:model="brand_primary_color" type="color" label="Colour"/><flux:input wire:model="registration_number" label="Companies House"/><flux:input wire:model="vat_number" label="VAT"/>@if($company?->logo_path)<img src="{{ Storage::url($company->logo_path) }}" class="max-h-20" alt="Current company logo">@endif</flux:card>@endif
<div class="flex justify-between border-t pt-4"><div>@if(!$company&&$step>1)<flux:button type="button" wire:click="back">Back</flux:button>@endif</div><div>@if(!$company&&$step<3)<flux:button type="button" variant="primary" wire:click="next">Next</flux:button>@else<flux:button type="submit" variant="primary">Save</flux:button>@endif</div></div></form>
<flux:modal name="address" class="min-w-[34rem]"><div class="space-y-4"><flux:heading>{{ $addressType==='head'?'Head Office':'Depot' }}</flux:heading>@unless($creatingAddress)<flux:select wire:model.live="selectedSiteId" variant="combobox" clearable label="Find an existing address"><x-slot name="input"><flux:select.input wire:model="addressSearch" placeholder="Search name, address or postcode..."/></x-slot>@foreach($siteOptions as $option)<flux:select.option :value="$option->id">{{ $option->name }} — {{ $option->formattedAddress() }}</flux:select.option>@endforeach<flux:select.option.create wire:click="createAddress" min-length="3">Create "<span wire:text="addressSearch"></span>"</flux:select.option.create></flux:select><flux:text>Search existing sites first. Create a new address only when no match is available.</flux:text>@else<flux:input wire:model="site_name" label="Name"/><flux:input wire:model="site_address_line_1" label="Address line 1"/><flux:input wire:model="site_address_line_2" label="Address line 2"/><div class="grid grid-cols-3 gap-3"><flux:input wire:model="site_town" label="Town"/><flux:input wire:model="site_county" label="County"/><flux:input wire:model="site_postcode" label="Postcode"/></div><div class="flex justify-end"><flux:button type="button" variant="primary" wire:click="saveAddress">Save address</flux:button></div>@endunless</div></flux:modal></x-pages::settings.layout></section>
